volumes:
  db_data:
  backend_logs:

services:
  db:
    image: postgres:15
    container_name: areal-hr-test-2024-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Spiridon_2017
      - POSTGRES_DB=areal_hr
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
    container_name: areal-hr-test-2024-backend
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - backend_logs:/var/log/backend
    environment:
      - NODE_ENV=development
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=areal_hr
      - PGUSER=postgres
      - PGPASSWORD=Spiridon_2017
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./app
    container_name: areal-hr-test-2024-frontend
    ports:
      - "9000:9000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - VUE_ROUTER_MODE=history
      - VUE_APP_DEBUG=true
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: areal-hr-test-2024-nginx
    ports:
      - "80:80"
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/spa:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
